apiVersion: v1
kind: Service
metadata:
  name: whisper-backend-service
  namespace: oitresearch-whisper-test
spec:
  selector:
    app: whisper-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30009
  type: NodePort
