apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-backend
  template:
    metadata:
      labels:
        app: whisper-backend
    spec:
      containers:
        - name: whisper-backend
          image: mlangstonsmith/whisper-backend:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: HTTP_PROXY
              value: "http://webproxy.smu.edu:3128"
            - name: HTTPS_PROXY
              value: "http://webproxy.smu.edu:3128"
            - name: NO_PROXY
              value: ".smu.edu,10.0.0.0/8,129.119.0.0/16,104.150.0.0/16,172.29.0.0/16,172.30.0.0/16,.svc,.cluster.local,127.0.0.0/8,192.168.0.0/16"