apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/client-body-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
  name: whisper-api
  namespace: oitresearch-whisper-test
spec:
  ingressClassName: nginx
  rules:
    - host: whisper.smu.edu
      http:
        paths:
          - backend:
              service:
                name: whisper-backend-service
                port:
                  number: 8000
            path: /transcribe
            pathType: Prefix
