apiVersion: v1
kind: Service
metadata:
  name: whisper-frontend-service
  namespace: oitresearch-whisper-test
spec:
  selector:
    app: whisper-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
  type: NodePort
