apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-frontend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-frontend
  template:
    metadata:
      labels:
        app: whisper-frontend
    spec:
      containers:
        - name: whisper-frontend
          image: mlangstonsmith/whisper-frontend:dev2
          ports:
            - containerPort: 8501
          imagePulllPolicy: Always
