apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-backend-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-backend
  template:
    metadata:
      labels:
        app: whisper-backend
    spec:
      containers:
        - name: whisper-backend
          image: "{{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.backend.gpus }}
          imagePulllPolicy: Always
          env:
            - name: HTTP_PROXY
              value: {{ .Values.backend.proxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.backend.proxy }}
            - name: NO_PROXY
              value: {{ .Values.backend.no_proxy }}