apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/connection-proxy-header: upgrade
    nginx.ingress.kubernetes.io/enable-websocket: 'true'
    nginx.ingress.kubernetes.io/proxy-http-version: '1.1'
    nginx.ingress.kubernetes.io/upgrade: websocket
    nginx.ingress.kubernetes.io/client-body-timeout: {{ .Values.frontend.ingress.nginx.client-body-timeout }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.frontend.ingress.nginx.proxy-body-size }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.frontend.ingress.nginx.proxy-connect-timeout }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.frontend.ingress.nginx.proxy-rs-timeout }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.frontend.ingress.nginx.proxy-rs-timeout }}
  name: whisper
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.ingress.cname }}
      http:
        paths:
          - backend:
              service:
                name: whisper-frontend-service
                port:
                  number: {{ .Values.frontend.ingress.port }}
            path: /
              pathType: Prefix
               