apiVersion: v1
kind: Service
metadata:
  name: whisper-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: whisper-frontend
  ports:
  - port: 80
    targetPort: 8501
  type: ClusterIP
