apiVersion: v1
data:
  SplunkHECToken: {{ required .Values.splunk.secret }}
kind: Secret
metadata:
  name: splunk-token
  namespace: {{ .Values.namespace }}
type: Opaque
--
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: splunk-oitresearch
  namespace: {{ .Values.namespace }}
spec:
  splunkHec:
    hec_host: ssplunk7ix01.smu.edu
    hec_port: 8088
    hec_token:
      valueFrom:
        secretKeyRef:
          key: SplunkHECToken
          name: splunk-token
    index: oit_kub_acad_oitresearch
    insecure_ssl: true
    protocol: https
    source: containerlogs
--
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: log-flow-whisper-test
  namespace: {{ .Values.namespace }}
spec:
  globalOutputRefs: []
  localOutputRefs:
    - splunk-oitresearch
